apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Project2-cluster-vpc
  region: us-east-1

vpc:
  id: vpc-0c02501d163c7dd0b
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0ad4f57be8e404868
      us-east-1b:
        id: subnet-0a347484929221061
    private:
      us-east-1a:
        id: subnet-06cdcf51eedfd4e09
      us-east-1b:
        id: subnet-075b472b5a42218d0

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
