apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: example-project
        image: aimh/classproject:latest
        ports:
            - containerPort: 8080
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: example-entrypoint
  namespace: default
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 8080
