apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-demo
  namespace: default
spec:
  replicas: 1
    selector:
    matchLabels:
      dockerdeploy: web
  template:
    metadata:
      labels:
        dockerdeploy: web
    spec:
      containers:
      - name: example-project
        image: app-container
---
apiVersion: v1
kind: Service
metadata:
  name: example-entrypoint
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
