apiVersion: v1
kind: Pod
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  containers:
    - name: kubernetesmicrosevice
      image: 485102483348.dkr.ecr.us-east-1.amazonaws.com/kubernetes-microservice:latest
      ports:
        - containerPort: 8080
